Sprint 10 pull request
icydtw/imageFeedApplication pull request #3
Opened 2023-02-21 06:24 UTC by icydtw

10 спринт: API Unsplash, OAuth 2.0, WebView, KVO, запросы, splash-screen.

2023-02-22 07:21 UTC, protos17 requested changes

2023-02-22 07:21 UTC, protos17 commented on imageFeedApplication/Auth/AuthViewController.swift
> +class AuthViewController: UIViewController, UIWebViewDelegate {
Давай проставлять ключевое слово `final` классам для ускорения работы компилятора.
Это нужно для оптимизация работы компилятора: ты явно сообщаешь о том, 
что класс не планируется расширять наследованием. 
В таком случае комплятор будет быстрее находить адрес ячейки памяти при вызове функции.
Эта тема про диспетчеризацию, если интересно, можно почитать здесь:
https://habr.com/ru/post/673400/
https://habr.com/ru/company/simbirsoft/blog/673636/

2023-02-22 07:21 UTC, protos17 commented on imageFeedApplication/Auth/AuthViewController.swift
> +    let authViewID = "ShowWebView"
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-02-22 07:21 UTC, protos17 commented on imageFeedApplication/Auth/OAuth2Service.swift
> +class OAuth2Service {
Класс без наследования стоит указать как final

2023-02-22 07:21 UTC, protos17 commented on imageFeedApplication/Auth/OAuth2Service.swift
> +let unsplashPostRequestURL = "https://unsplash.com/oauth/token"
Вне классов не стоит хранить ни какие константы, лучше перенести это в соответствующий файл Constants

2023-02-22 07:21 UTC, protos17 commented on imageFeedApplication/Auth/OAuth2Service.swift
> +                completion(.failure("Ошибка номер \(response.statusCode)" as! Error))
Рекомендую для ошибок создать собственный энам с ошибками и передавать его, например: 
enum NetworkError: Error {
    case responseError(error: String)
    case decodeError(error: String)
}

2023-02-22 07:21 UTC, protos17 commented on imageFeedApplication/Auth/OAuth2Service.swift
> +                completion(.failure("Ошибка обработки данных" as! Error))
Здесб тоже пригодился бы энам со своими ошибками, что поможет точно определять, какая именно ошибка пришла

2023-02-22 07:21 UTC, protos17 commented on imageFeedApplication/Auth/WebViewViewController.swift
> +import Foundation
При импорте UIKit можно не импортировать Foundation, потому что первая содержит в себе вторую

2023-02-22 07:21 UTC, protos17 commented on imageFeedApplication/Auth/WebViewViewController.swift
> +let UnsplashAuthorizeURLString = "https://unsplash.com/oauth/authorize"
Стоит тоже перенести в файл с константами

2023-02-22 07:21 UTC, protos17 commented on imageFeedApplication/Auth/WebViewViewController.swift
> +    @IBAction func didTapBackButton(_ sender: Any) {
Для IBAction стоит тоже указывать private

2023-02-22 07:21 UTC, protos17 commented on imageFeedApplication/Auth/WebViewViewController.swift
> +    @IBOutlet var progressView: UIProgressView!
Для IBOutlet тоже стоит указать private

2023-02-22 07:21 UTC, protos17 commented on imageFeedApplication/OAuth2TokenStorage.swift
> +class OAuth2TokenStorage {
Необходимо указать как final

2023-02-22 07:21 UTC, protos17 commented on imageFeedApplication/OAuth2TokenStorage.swift
> +    let userDefaults = UserDefaults.standard
Необходимо указать как private

2023-02-22 07:21 UTC, protos17 commented on imageFeedApplication/OAuth2TokenStorage.swift
> +class OAuth2TokenStorage {
Для корректной реализации паттерна синглтон рекомендую сделать так:
final class OAuth2TokenStorage {
static let shared = OAuth2TokenStorage()
private init() {}
...
}

2023-02-22 07:21 UTC, protos17 commented on imageFeedApplication/Profile/ProfileViewController.swift
> +        OAuth2TokenStorage().token = nil
При реализации синглтона код изменится для вызова: OAuth2TokenStorage.shared.token = nil

2023-02-22 07:21 UTC, protos17 commented on imageFeedApplication/SplashViewController/SplashViewController.swift
> +import Foundation
Можно удалить Foundation

2023-02-22 08:02 UTC, icydtw commented on imageFeedApplication/SplashViewController/SplashViewController.swift
> +            else { fatalError("Failed to prepare for \(ShowAuthenticationScreenSegueIdentifier)") }
Спасибо! Где можно побольше почитать про ошибки? Про их обработку?

2023-02-22 08:10 UTC, icydtw commented on imageFeedApplication/OAuth2TokenStorage.swift
> +class OAuth2TokenStorage {
Не совсем понимаю, а что тогда должно быть внутри init?

2023-02-22 08:11 UTC, icydtw commented on imageFeedApplication/OAuth2TokenStorage.swift
> +class OAuth2TokenStorage {
Аа, понял, это чтобы не позволить никому создать экземпляр OAuth2TokenStorage.

2023-02-22 13:25 UTC, protos17 requested changes

2023-02-22 13:25 UTC, protos17 commented on imageFeedApplication/Auth/AuthViewController.swift
> +                fatalError("Ошибка!")
Рекомендую никогда не использовать fataError в проекте, советую заменить на assertionFailure

2023-02-22 13:25 UTC, protos17 commented on imageFeedApplication/Auth/AuthViewController.swift
> +import Foundation
Можно убирать Foundation из импорта, если импортирован UIKit, потому что он содержит в себе Foundation

2023-02-22 13:25 UTC, protos17 commented on imageFeedApplication/SplashViewController/SplashViewController.swift
> +        DispatchQueue.main.async {
Сейчас весь fetchAuthToken вызывается на главном потоке,  но мы не должны делать сетевые запросы на главном потоке, а лишь completion

2023-02-22 13:25 UTC, protos17 commented on imageFeedApplication/SplashViewController/SplashViewController.swift
> +                guard let self = self else { return }
Или здесь в замыкании вызывать на главном потоке или внутри самого метода при вызове completion(...) вызывать в главном потоке

2023-02-22 13:25 UTC, protos17 commented on imageFeedApplication/Auth/OAuth2Service.swift
> +                completion(.success(successResult.accessToken))
Можно каждый вызов completion вызывать на главном потоке, но никак не весь сетевой вызов

2023-02-22 14:17 UTC, icydtw commented on imageFeedApplication/Auth/OAuth2Service.swift
> +                completion(.success(successResult.accessToken))
Я поправил, Вы можете посмотреть, я правильно понял или нет? Посмотрел ещё раз в методичке.

2023-02-23 10:21 UTC, protos17 approved these changes

2023-02-23 12:37 UTC, merged